scrape_configs:
  - job_name: tendermint
    scrape_interval: 5s
    static_configs:
      - targets: ["canto:26660"]
  - job_name: cosmos-sdk
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ["prometheus"]
    static_configs:
      - targets: ["canto:1317"]
  - job_name: traefik
    scrape_interval: 5s
    static_configs:
      - targets: ["traefik:8899"]
  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]
