name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DOCKERHUB_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/canto
  GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/canto
  SHOULD_PUBLISH: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) }}

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write
    env:
      LATEST_VERSION: 8.1.3
    strategy:
      matrix:
        version: [
          thomas/archive-patch,
          1.0.0,
          2.0.0,
          3.0.0,
          4.0.0,
          5.0.0,
          5.0.2,
          6.0.0,
          7.0.0,
          7.0.1,
          7.1.0,
          8.0.0,
          8.1.0,
          8.1.1,
          8.1.3,
        ]
      # prevents from reaching Docker Hub pull rate limit
      max-parallel: 5
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      # Login to DockerHub
      - uses: docker/login-action@v3
        if: ${{ env.SHOULD_PUBLISH == 'true' }}
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Login to GHCR
      - uses: docker/login-action@v3
        if: ${{ env.SHOULD_PUBLISH == 'true' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Environment Variables
        run: |
          VERSION=${{ matrix.version }}
          TAG_VERSION=$VERSION
          VERSION_PREFIX=v
          # Set Go version
          MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
          if [ "$MAJOR_VERSION" -ge "8" ]; then
            echo "GO_VERSION=1.21" >> $GITHUB_ENV
          else
            echo "GO_VERSION=1.20" >> $GITHUB_ENV
          fi
          # custom tag as 2.0.2, since upstream didn't tag it, refs:
          # https://github.com/Canto-Network/Canto/issues/97
          if [ "$VERSION" == "thomas/archive-patch" ]; then
            VERSION_PREFIX=
            TAG_VERSION=2.0.2
          fi
          echo "VERSION_PREFIX=$VERSION_PREFIX" >> $GITHUB_ENV
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "PREFIXED_VERSION=$VERSION_PREFIX$VERSION" >> $GITHUB_ENV
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ env.DOCKERHUB_IMAGE }}
            ${{ env.GHCR_IMAGE }}
          tags: |
            type=raw,value=${{ env.TAG_VERSION }}
            type=raw,value=latest,enable=${{ env.TAG_VERSION == env.LATEST_VERSION }}
      - uses: docker/build-push-action@v6
        with:
          push: ${{ env.SHOULD_PUBLISH == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.PREFIXED_VERSION }}
            GO_VERSION=${{ env.GO_VERSION }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            type=registry,ref=${{ env.DOCKERHUB_IMAGE }}:${{ env.TAG_VERSION }}
            type=registry,ref=${{ env.GHCR_IMAGE }}:${{ env.TAG_VERSION }}
          cache-to: ${{ env.SHOULD_PUBLISH == 'true' && format('type=registry,ref={0}:{1},mode=max', env.DOCKERHUB_IMAGE, env.TAG_VERSION) || '' }}
  update-readme:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/dockerhub-description@v4
        if: ${{ env.SHOULD_PUBLISH == 'true' }}
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_IMAGE }}
          readme-filepath: README.md
