name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    env:
      TARGET_BRANCH: refs/heads/main
      LATEST_VERSION: 8.1.3
    strategy:
      matrix:
        version: [
          1.0.0,
          2.0.0,
          3.0.0,
          4.0.0,
          5.0.0,
          5.0.2,
          6.0.0,
          7.0.0,
          7.0.1,
          7.1.0,
          8.0.0,
          8.1.0,
          8.1.1,
          8.1.3,
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: ${{ github.event_name == 'push' && (github.ref == env.TARGET_BRANCH || startsWith(github.ref, 'refs/tags/')) }}
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Go version
        run: |
          VERSION=${{ matrix.version }}
          MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
          if [ "$MAJOR_VERSION" -ge "8" ]; then
            echo "GO_VERSION=1.21" >> $GITHUB_ENV
          else
            echo "GO_VERSION=1.20" >> $GITHUB_ENV
          fi
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/canto
          tags: |
            type=raw,value=${{ matrix.version }}
            type=raw,value=latest,enable=${{ matrix.version == env.LATEST_VERSION }}
      - uses: docker/build-push-action@v6
        env:
          VERSION: ${{ matrix.version }}
        with:
          push: ${{ github.event_name == 'push' && (github.ref == env.TARGET_BRANCH || startsWith(github.ref, 'refs/tags/')) }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}
            GO_VERSION=${{ env.GO_VERSION }}
          platforms: linux/amd64,linux/arm64
